INSERT INTO USER(UID, EMAIL, NAME, PASSWORD) VALUES(1,'honux@codesquad.kr','정호영','3241');
INSERT INTO USER(UID, EMAIL, NAME, PASSWORD) VALUES(2,'whiteship@ms.com','백기선','3241');
INSERT INTO USER(UID, EMAIL, NAME, PASSWORD) VALUES(3,'pobi@conan.com','박재성','3241');
INSERT INTO USER(UID, EMAIL, NAME, PASSWORD) VALUES(4,'tobi@god.au','이일민','3241');