INSERT INTO USER(EMAIL, NAME, PASSWORD) VALUES('honux@codesquad.kr','정호영','3241');
INSERT INTO USER(EMAIL, NAME, PASSWORD) VALUES('whiteship@ms.com','백기선','3241',);
INSERT INTO USER(EMAIL, NAME, PASSWORD) VALUES('pobi@conan.com','박재성','3241');
INSERT INTO USER(EMAIL, NAME, PASSWORD) VALUES('tobi@god.au','이일민','3241');

INSERT INTO QUESTION(AUTHOR, TITLE, QUESTION, DATE_CREATED) VALUES ('정호영', '재밌는 게임 추천 좀', 'PS4 용으로 부탁드려요', '2019-1-1');
INSERT INTO QUESTION(AUTHOR, TITLE, QUESTION, DATE_CREATED) VALUES ('정호영', '재밌는 책 추천', 'PS3 용으로 부탁드려요', '2019-1-2');
INSERT INTO QUESTION(AUTHOR, TITLE, QUESTION, DATE_CREATED) VALUES ('정호영', '재밌는 언어 추천', 'PS2 용으로 부탁드려요', '2019-1-3');
INSERT INTO QUESTION(AUTHOR, TITLE, QUESTION, DATE_CREATED) VALUES ('정호영', '도배 죄송', 'PS1 용으로 부탁드려요', '2019-1-3');
INSERT INTO QUESTION(AUTHOR, TITLE, QUESTION, DATE_CREATED) VALUES ('정호영', '마운트 이스케이프가 잘 안 됩니다', 'PS1 용으로 부탁드려요', '2019-1-4');
INSERT INTO QUESTION(AUTHOR, TITLE, QUESTION, DATE_CREATED) VALUES ('박재성', '경운기 운전법 가르쳐 주세요', '현실 용으로 부탁드려요', '2019-1-4');